PlaceOS/models

src/engine-models/authority.cr

This is to make it compatible with the ruby version of this model.
I assume the use of `JSON::Any` is technically fine here?

fix(authority): add timestamps and use `JSON::Any`

---

spec/settings_spec.cr
src/models/settings.cr

`parent_type` is to to improve resolution of setting dependencies
@MrYuion: when we a settings is created for a model set `parent_type` to one of `control_system|zone|module|driver`

improvement(settings): add a required `parent_type` field

---

shard.yml
spec/control_system_spec.cr
src/placeos-models/control_system.cr

ControlSystem features are now a Set(String). They should be maintained like Zone tags
@benhoad @MrYuion This change is relevant to PlaceOS/backoffice/issues/69
Fixes #28

fix(control-system): generate resolved module names

---

shard.yml
spec/authority_spec.cr
spec/generator.cr
src/placeos-models/authority.cr

Add `has_many` relation with `destroy` dependency to `PlaceOS::Model::Authority` for...
- `PlaceOS::Model::OAuthAuthentication`
- `PlaceOS::Model::LdapAuthentication`
- `PlaceOS::Model::SamlAuthentication`
Fixes #27

fix(authority): destroy dependent users, oauth strats, ldap strats, and saml strats

---

src/placeos-models/settings.cr

Previous `Error` reference was resolving to a Neuroplastic::Error
due to inclusing in ModelBase.
Authored by @KimBurgess

fix(settings): raise Model::Error on failed parse

---

shard.yml
spec/generator.cr
spec/settings_spec.cr
src/placeos-models/module.cr
src/placeos-models/settings.cr
src/placeos-models/user_jwt.cr

Migrate to `case... in` statements where possible to ensure branch coverage of type unions and enums.

refactor: use `case...in` over `case...when` where possible

---

shard.yml
spec/control_system_spec.cr
src/placeos-models/control_system.cr
src/placeos-models/module.cr

Pulls out `Module`'s `custom_name` and `name` from the `ControlSystem`'s `features` set, which is regenerated on save.

fix(control_system): remove module from features in `remove_module`

---

shard.yml
spec/module_spec.cr
src/placeos-models/module.cr

adds `Module.logic_for(control_system_id : String)` to query for logic modules with a direct `ControlSystem` association

feat(module): #logic_for query by parent control_system

---

shard.yml
spec/module_spec.cr
src/placeos-models/module.cr

Adds a validator to `PlaceOS::Model::Module` to ensure only `Logic` modules have an associated parent system.

fix(module): ensure only logic modules have parent systems

---

shard.yml
spec/module_spec.cr
src/placeos-models/module.cr

Previously, a mutation in service drivers set `@udp` and `@tls` to `nil` when these attributes are typed as `Bool`.
In addition, the mutations for each module type have been spec'd.

test: module conditions

---

shard.yml
src/placeos-models/edge.cr

Catch errors raised by invalid base64 inputs to `Edge.validate_token?`

fix(edge): catch errors from invalid base64

---

shard.yml
src/placeos-models/base/model.cr
src/placeos-models/repository.cr

- `Repository::Type` was not correctly serialising via to `to_reql`
- `SubModel` was not serialising to a `JSON::Any`, fix utilises the unfortunate `JSON.parse(self.to_json)` hack out of necessity (correct serialisations, etc)

fix: to_reql

---

shard.yml
spec/helper.cr
spec/settings_spec.cr
src/placeos-models/edge.cr
src/placeos-models/error.cr
src/placeos-models/settings.cr

- Adds validation to `Setting#settings_string`
- Adds `cause` to `Model::Error` 
- Removes `_` char from `Edge#secret` on generation, this was interfering with the separator
Closes #76

fix: validate settings

---

shard.yml
spec/edge_spec.cr
src/placeos-models/edge.cr

[Tests](https://github.com/PlaceOS/models/runs/2218430663#step:6:13) occasionally revealed a bug in the generation/validation of `PlaceOS::Model::Edge` secrets.
The cause was a clash in the separator (`_`) and chars in the database id. 
This PR ensures the database id is free from URL unsafe chars, and strips `~`, which is the new separator.
Closes #83

fix(edge): ensure seperator not present in secret or id

---

shard.yml
spec/trigger_spec.cr
src/placeos-models/trigger/conditions.cr

Move the comparison validation from set inclusion to language-level type safety via an enum. 
Also moves the `compare` method into the enum itself.

refactor: factor comparison operators into an enum

---

spec/control_system_spec.cr
spec/zone_spec.cr
src/placeos-models/zone.cr

Ensure Zones with existing names are not added and add some tests to confirm name uniqueness for Zones & Control Systems
Closes [PlaceOS/PlaceOS#70](https://github.com/PlaceOS/PlaceOS/issues/70)

fix: ensure unique zone names

---

spec/doorkeeper_app_spec.cr
src/placeos-models/doorkeeper_application.cr

- Adds validation to ensure domains have applications with unique names and URLs
- Validation raises a more descriptive error message for the front end
Closes PlaceOS/rest-api#133

feat(doorkeeper): ensure uniqueness of name + URL

---

shard.yml
src/placeos-models/driver.cr
src/placeos-models/json_schema.cr

`rubber-soul` was incorrectly mapping the type for the embedded objects `json_schema` and `schema` as we convert them to `JSON::Any` on serialisation from a raw string.
This PR adds type hints for `rubber-soul`

fix: set es-type for schema fields

---

spec/api_key_spec.cr
spec/generator.cr
src/placeos-models/api_key.cr
src/placeos-models/edge.cr
src/placeos-models/user.cr

allows generation of an API key where the key is never saved in the database for security
The idea is that the token generates a decoded JWT token that will be used against the controllers - so only a minor change to the authentication layer is required

feat: add API key model

---

CHANGELOG.md
shard.yml
spec/user_spec.cr
src/placeos-models/user.cr

Related to https://github.com/PlaceOS/models/issues/108
* **user:**
* `User.find_by_email` and `User.find_by_emails` are now case-insensitive.

feat(user): perform a case insensitive email lookup

---

shard.yml
src/placeos-models/base/jwt.cr

primarily for MQTT integration, after connection is validated we only need the JWT for permission checking and don't want to deny access when the token expires (the connection isn't changing)

feat(base jwt): allow optional validation

---

shard.yml
spec/settings_helper_spec.cr
src/placeos-models/settings.cr
src/placeos-models/utilities/settings_helper.cr

Technically this is a breaking change.
However, it is more expected behaviour.
Previously, an encrypted value could silently override a setting of lower privilege.
Closes #119

fix(settings): merge down encryption levels

---

shard.yml
src/placeos-models/settings.cr
src/placeos-models/utilities/settings_helper.cr

#137 introduced a change that messed up the order settings were returned in via `#master_settings_query`.

fix(settings): return previous order of settings

---

spec/api_key_spec.cr
src/placeos-models/api_key.cr
src/placeos-models/error.cr
src/placeos-models/module.cr
src/placeos-models/settings.cr

A breaking change.
This places all errors beneath `PlaceOS::Model::Error`

refactor!(error): better namespacing for errors

---

.github/workflows/changelog.yml
.github/workflows/validate-pr.yml
spec/api_key_spec.cr
src/placeos-models/api_key.cr

Fetch the SaaS key even if it is already present in the remote.

fix(api_key): no error if SaaS key already exists, add `public` scope

---

README.md
spec/metadata_spec.cr
spec/module_spec.cr
spec/settings_spec.cr
spec/utilities/settings_helper_spec.cr
src/placeos-models/control_system.cr
src/placeos-models/driver.cr
src/placeos-models/json_schema.cr
src/placeos-models/metadata.cr
src/placeos-models/module.cr
src/placeos-models/settings.cr
src/placeos-models/user.cr
src/placeos-models/utilities/last_modified.cr
src/placeos-models/utilities/metadata_helper.cr
src/placeos-models/utilities/settings_helper.cr
src/placeos-models/utilities/versions.cr
src/placeos-models/zone.cr

- Adds a generalised model version module
- Adds generalised history module to `Metadata`
**Benefits**
Generalises the logic of versions, and makes it simpler to add versioning to a model
**Possible drawbacks**
- Queries in the model will need to be scoped to ensure that versions don't pollute the queries for master versions.
- Changes to interface: `master_settings` is now `settings`
- Changes to interface: `settings` is now `settings_and_versions`
- Closes #150
- Closes #151

feat(metadata): add `#history`

---

spec/metadata_spec.cr
src/placeos-models/utilities/versions.cr

Returns `offset` and `limit` to prevent breaking the API interface, and support larger history sizes.
**Benefits**
Keeps interface stable

fix(versions#history): restore `offset` and `limit`

---

spec/generator.cr
spec/metadata_spec.cr
src/placeos-models/metadata.cr

Ensure model referenced by `parent_id` exists
- Closes https://github.com/PlaceOS/rest-api/issues/245

feat(metadata): validate parent exists

---

src/placeos-models/metadata.cr

Adds `id` parameter to the `Metadata` json response object
**Benefits**
Enables the `/:id/history` endpoint
**Possible drawbacks**
Leaking ID for a single route feels hacky

feat(metadata): add `id` to `Metadata::Interface`

---

spec/metadata_spec.cr
spec/user_spec.cr
src/placeos-models/metadata.cr
src/placeos-models/utilities/last_modified.cr

Conform `Metadata` history response to other `Metadata` responses, i.e. an object keyed by `name` with values of the desired response.
**Benefits**
Prevent awkward API change by addition of `id` in the `Metadata::Interface` in #157

feat(metadata): add `Metadata.build_history`

---

src/placeos-models/metadata.cr

Quick fix, `parent_id` can be null, this will be validated later

fix(Metadata.user_can_create?): looser `parent_id` restriction

---

.github/workflows/validate-pr.yml
src/placeos-models/metadata.cr

Validation was breaking due to a cast in the `validate_parent_exists` validation

fix(metadata): skip parent validation if no `parent_id`

---

shard.yml
spec/metadata_spec.cr
src/placeos-models/metadata.cr

Adds the ability to query `Metadata` documents.
Supported query types...
- `association`, where `association` is one of `system`, `zone`, or `user`
- `starts_with`
- `equals`
- `key_missing`
Internally, `Metadata::Query` is built from a URL param key-value pair, of the form `<type>[<key>]=<value>`.
`key` and `value` can be composed of alphanumeric, `-`, `.`, `_`, or `~` characters.
`key` can address nested keys, with `.` separating components of the key path.
- https://github.com/PlaceOS/rest-api/issues/250

feat(metadata): implement queries

---

spec/metadata_spec.cr
src/placeos-models/metadata.cr

- Ensure that special regex characters are escaped
- URI decode params in the parse step
- Allow `@` and ` ` after decoding
This fixes the previously broken equals query.

fix(metadata#query): allow `@` and ` ` in keys and values

---

src/placeos-models/edge.cr

Allow passing of the `x_api_key` field in the response for edge creation but don't persist it in the edge model.
**Benefits**
Backoffice (and any other frontend) will be able to display the api key to the user upon creation of an edge.

feat(edge): add `#to_key_json`

---

spec/metadata_spec.cr
src/placeos-models/metadata.cr
src/placeos-models/utilities/versions.cr

Adds pagination to `Metadata.query`. Also corrects some potential unexpected behaviour with negative pagination ranges.
**Benefits**
Paged results for Metadata queries.
- https://github.com/PlaceOS/rest-api/issues/263

feat(metadata): add pagination

---

shard.yml
src/placeos-models/repository.cr

for differentiating between the target `commit_hash` and what is currently in place.
This allows interfaces to remain at `HEAD` with only changes to `deployed_commit_hash` occuring for feedback

feat(repository): add deployed_commit_hash

---

shard.yml
src/placeos-models/repository.cr

deployed_commit_hash for indicating the current commit level
we keep commit_hash_will_change as deployed_commit_hash might already be nil and commit_hash is the important bit of information

fix(repository): pull! should use deployed_commit_hash

---

src/placeos-models/executable.cr

Limits the length of the commit hash to 7 chars.
**Benefits**
Normalizes lookups

fix(executable): short commit

---

shard.yml
src/placeos-models/user.cr

applications that shouldn't have access can be limited via scopes
This is the first step in our plan to help NTT move away from listing users via a driver

feat(user): user metadata should be available to authenticated users

---

src/placeos-models/authority.cr

Adds `default_app` with default of `/backoffice/` when creating a domain
**Benefits**
Avoids having to manually set it.
Kubernetes ingress overrides which currently handle this will be removed.
https://acaprojects.atlassian.net/browse/PPT-108

chore(authority): add default_app to config

---

src/placeos-models/asset.cr
src/placeos-models/asset_instance.cr

Merge commit https://github.com/PlaceOS/models/commit/fb436e5bb2a6f0dbf201dd25ef8d3c2994f09262 breaks `asset.cr` and `asset_instance.cr`. This PR is to revert changes made to these two files.
- `Time::EpochConverter` returns a `Time?` so it will break on attributes which doesn't use (Type | Nil) union.
- `PlaceOS::Model::Timestamps::EpochConverter` returns a `Time`, so it should be used for attributes which are not expecting any nil value.

fix: merge commit fb436e breaks asset and asset_instance

---

spec/control_system_spec.cr
src/placeos-models/control_system.cr

so if a module is in another system then deleting the current system will not remove the module from the other system

fix(control_system): should only remove modules only in system [PPT-1102]

---

migration/db/migrations/202501211046000_alter_tenant_add_parent.sql
src/placeos-models/tenant.cr

so we can have bookings shared between domains

feat(tenant): delegate tenant configuration

---

migration/db/migrations/202506061335000_alter_uploads_user_photo_locatable.sql
shard.yml
src/placeos-models/upload.cr
src/placeos-models/user.cr

tags for uploads allowing us to filter by upload use cases

feat: user photo upload and locatable flag [PPT-2038]
