PlaceOS/models

- spec/zone_spec.cr
- src/models/zone.cr
in support of the new Staff App
> feat(zone): add support for hierarchies

- src/models/control_system.cr
- src/models/zone.cr
to reduce the amount of custom config that is requied by the staff app
> feat: add some common metadata

- src/models/doorkeeper_application.cr
a secret should always be generated, might as well default skip authorisation to true as we typically use this.
> fix(doorkeeper application): UID is an MD5 of the redirect

- src/placeos-models/user.cr
> feat(user): add groups attribute

- .travis.yml
- spec/user_spec.cr
- src/placeos-models/user.cr
> fix(user): password saving on JSON parse

- shard.yml
- spec/metadata_spec.cr
- src/placeos-models/metadata.cr
- src/placeos-models/utilities/json_string_converter.cr
- src/placeos-models/utilities/semver_converter.cr
migration:
```js
r
.db('rethinkdb_development')
.table('metadata')
.replace(r.row.merge({details: r.row('details').toJSON()})
```
> refactor(metadata): serialize `Metadata#details` to String

- shard.yml
- src/placeos-models/broker.cr
- Ensure `Broker`s are unique by name
> improvement(broker): unique by name

- shard.yml
- src/placeos-models/module.cr
Add a `keyword` subfield for `Module`'s name.
This enables sorting by name while performing fuzzy search on a `Module`.
> improvement(module): add name keyword subfield

- shard.yml
- src/placeos-models/base/jwt.cr
- src/placeos-models/utilities/encryption.cr
- `JWT` encodes via `JWT_SECRET`, decodes via `JWT_PUBLIC` (with `JWT_SECRET` fallback) 
- A warning is logged if the `JWT`/`Encryption` modules are configured with default secrets
> fix(jwt): default to PUBLIC_KEY in decode and PRIVATE_KEY in encode

- src/placeos-models/metadata.cr
- src/placeos-models/user.cr
> feat(metadata): add support for user level metadata

- shard.yml
- spec/edge_spec.cr
- spec/generator.cr
- spec/module_spec.cr
- src/placeos-models/doorkeeper_application.cr
- src/placeos-models/edge.cr
- src/placeos-models/module.cr
- src/placeos-models/settings.cr
- src/placeos-models/utilities/encryption.cr
Model for an edge node drafted up here for discussion.
Resolves PlaceOS/edge-connect#11
> feat(edge): add edge model that represents an edge node

- shard.yml
- spec/generator.cr
- spec/repository_spec.cr
- src/placeos-models/repository.cr
Fixes PlaceOS/backoffice/issues/121
> fix(repository): validate no spaces in `folder_name`

- shard.yml
- src/placeos-models/module.cr
adds `Module.on_edge(edge_id : String)`
> feat(module): fetch modules by edge_id

- shard.yml
- spec/edge_spec.cr
- src/placeos-models/edge.cr
- src/placeos-models/module.cr
- src/placeos-models/utilities/encryption.cr
Adds `PlaceOS::Model::Edge#check?(secret)` for the purpose of validating secrets of connecting edge nodes.
> feat(edge): secret validation

- shard.yml
- spec/edge_spec.cr
- src/placeos-models/edge.cr
Helper to generate a token in the format expected by an `edge` node
> feat(edge): add token generation method

- shard.yml
- spec/user_spec.cr
- src/placeos-models/module.cr
- src/placeos-models/user.cr
- Ensure that privilege can only be assigned by admin users
- Refactor admin managed attribute assignments into `PlaceOS::Model::User`
- Reorganisation of `PlaceOS::Model::User`'s methods
> Fix: admin updates to User

- shard.yml
- spec/user_spec.cr
- src/placeos-models/user.cr
- Query for multiple users by emails under an authority
- Expose User's groups publically
> feat(user): add a bulk user by email query

- shard.yml
- src/placeos-models/module.cr
> fix(module): minor style change

- shard.yml
- src/placeos-models/control_system.cr
Closes PlaceOS/rest-api/issues/100
> feat(control_system): add images[] to hold references to image URLs

- shard.yml
- src/placeos-models/edge.cr
- src/placeos-models/repository.cr
Sets a commit hash on interface repositories that the `frontends` loader will force pull on
> fix(interface): explicitly set a pull commit

- spec/repository_spec.cr
- src/placeos-models/base/model.cr
- src/placeos-models/control_system.cr
- src/placeos-models/module.cr
- src/placeos-models/repository.cr
- src/placeos-models/utilities/validation.cr
A slight DRY out of uri validation logic
> refactor(validation): add a helper for URI validation

- shard.yml
- spec/control_system_spec.cr
- spec/module_spec.cr
- spec/repository_spec.cr
- spec/settings_spec.cr
- spec/user_spec.cr
- src/placeos-models/control_system.cr
- src/placeos-models/driver.cr
- src/placeos-models/module.cr
- src/placeos-models/settings.cr
Adds a field to driver to store the last failed compilation output.
> feat: compilation output

- shard.yml
- src/placeos-models/metadata.cr
Adds a field to hold a schema for metadata.
> feat(metadata): add schema field

- shard.yml
- spec/helper.cr
- src/placeos-models/base/model.cr
- src/placeos-models/broker.cr
- src/placeos-models/driver.cr
- src/placeos-models/edge.cr
- src/placeos-models/module.cr
- src/placeos-models/repository.cr
- src/placeos-models/settings.cr
- src/placeos-models/trigger/conditions.cr
- src/placeos-models/user_jwt.cr
Updates to support crystal 1.0.0
> chore: crystal 1.0.0

- shard.yml
- src/placeos-models/driver.cr
Missed the value converter for `Driver` role.
> fix(driver): value converter for driver role

- shard.yml
- src/placeos-models/module.cr
> fix(module): force no tls only when udp

- shard.yml
- spec/generator.cr
- spec/repository_spec.cr
- src/placeos-models/control_system.cr
- src/placeos-models/module.cr
- src/placeos-models/user.cr
Adds logging for when modules are removed from control systems.
> feat: module system logging

- shard.yml
- spec/saml_authentication_spec.cr
This fixes an issue where deleted attributes would persist after update.
Closes PlaceOS/rest-api/issues/103
> test(saml_authentication): overwrite rather than merge `attribute_assignments`

- shard.yml
- spec/control_system_spec.cr
- spec/generator.cr
- spec/settings_spec.cr
- spec/user_jwt_spec.cr
- src/placeos-models/authority.cr
- src/placeos-models/broker.cr
- src/placeos-models/control_system.cr
- src/placeos-models/doorkeeper_application.cr
- src/placeos-models/driver.cr
- src/placeos-models/edge.cr
- src/placeos-models/ldap_authentication.cr
- src/placeos-models/metadata.cr
- src/placeos-models/module.cr
- src/placeos-models/oauth_authentication.cr
- src/placeos-models/repository.cr
- src/placeos-models/saml_authentication.cr
- src/placeos-models/settings.cr
- src/placeos-models/trigger.cr
- src/placeos-models/trigger/actions.cr
- src/placeos-models/trigger/conditions.cr
- src/placeos-models/trigger_instance.cr
- src/placeos-models/user.cr
- src/placeos-models/user_auth_lookup.cr
- src/placeos-models/user_jwt.cr
- src/placeos-models/zone.cr
Refactor across all models to ensure their syntax is up-to-date, consistent, and clear.
Methods have been batched beneath headings. This means attributes, callbacks, and validations are now clearly separated for each class.
> style: syntax touch up

- shard.yml
- spec/zone_spec.cr
- src/placeos-models/zone.cr
Use `.with_tag(tag : String)` to query for `PlaceOS::Model::Zone`s by their `tags` attribute.
> feat(zone): add `.with_tag` query

- spec/authority_spec.cr
- src/placeos-models/authority.cr
> fix(authority): allow raw domains to be set

- shard.yml
- src/placeos-models/trigger/conditions.cr
CRON isn't too useful without time zone support
> feat(trigger conditions): add support for timezones in CRON

- .github/workflows/ci.yml
- shard.yml
- src/placeos-models/version.cr
Adds a `Version` struct that each service will render under the `/version`  endpoint
> feat: add a `Version` struct for use across all services

- .github/workflows/ci.yml
- shard.yml
- src/placeos-models/version.cr
Adds platform version to `PlaceOS::Model::Version`
> feat: add platform version

- shard.yml
- src/placeos-models/control_system.cr
- src/placeos-models/driver.cr
- src/placeos-models/settings.cr
Corrects some elastic types that were incorrect
> fix(models): correct es types

- shard.yml
- spec/repository_spec.cr
- spec/user_spec.cr
- src/placeos-models/repository.cr
Adds encryption for `Repository#token` and `Repository#password`
> fix(repository): encryption for `password`, `token`

- shard.yml
- src/placeos-models/user.cr
Adds a groups only subject serializer
> feat(user): `to_groups_json`

- shard.yml
- src/placeos-models/authority.cr
- src/placeos-models/broker.cr
- src/placeos-models/control_system.cr
- src/placeos-models/doorkeeper_application.cr
- src/placeos-models/driver.cr
- src/placeos-models/edge.cr
- src/placeos-models/json_schema.cr
- src/placeos-models/ldap_authentication.cr
- src/placeos-models/metadata.cr
- src/placeos-models/module.cr
- src/placeos-models/oauth_authentication.cr
- src/placeos-models/repository.cr
- src/placeos-models/saml_authentication.cr
- src/placeos-models/trigger.cr
- src/placeos-models/user.cr
- src/placeos-models/zone.cr
Fix incorrect mapping for `name` attributes.
> fix: `name` es_type

- .github/workflows/ci.yml
- shard.yml
- src/placeos-models/authority.cr
- src/placeos-models/broker.cr
- src/placeos-models/control_system.cr
- src/placeos-models/doorkeeper_application.cr
- src/placeos-models/driver.cr
- src/placeos-models/edge.cr
- src/placeos-models/json_schema.cr
- src/placeos-models/ldap_authentication.cr
- src/placeos-models/metadata.cr
- src/placeos-models/module.cr
- src/placeos-models/oauth_authentication.cr
- src/placeos-models/repository.cr
- src/placeos-models/saml_authentication.cr
- src/placeos-models/trigger.cr
- src/placeos-models/user.cr
- src/placeos-models/zone.cr
This reverts commit 1155484ad53d117e735f2ba6b8b6ca06b95d5c53.
> revert!: `name` es_type

- .github/workflows/ci.yml
- shard.yml
- spec/repository_spec.cr
- src/placeos-models/repository.cr
Empty fields were getting encrypted.
> fix(repository): check presence before encrypting

- CHANGELOG.md
- shard.yml
- src/placeos-models/control_system.cr
- src/placeos-models/driver.cr
- src/placeos-models/module.cr
- src/placeos-models/settings.cr
- src/placeos-models/utilities/settings_helper.cr
- src/placeos-models/zone.cr
Adds `#settings_hierarchy` for all models with associated settings.
> fix: add `settings_hierachy`

- .github/workflows/ci.yml
- shard.yml
- src/placeos-models/api_key.cr
Elasticsearch type hints were missing for complex types in `ApiKey`
> fix(api_key): set es_types for complex types

- spec/generator.cr
- spec/settings_spec.cr
- src/placeos-models/settings.cr
> fix(settings): improve YAML validation

- shard.yml
- spec/repository_spec.cr
- src/placeos-models/repository.cr
> refactor(repository): remove `key`

- .github/workflows/ci.yml
- shard.yml
- src/placeos-models/utilities/encryption.cr
Exposes `secret` as an arg to `Encryption.encrypt` and `Encryption.decrypt`
> refactor(encryption): expose the secret in the arguments

- shard.yml
- spec/asset_instance_spe.cr
- spec/asset_instance_spec.cr
- spec/asset_spec.cr
- spec/generator.cr
- src/placeos-models/asset.cr
- src/placeos-models/asset_instance.cr
- src/placeos-models/user.cr
> feat: add models required for asset manager

- shard.yml
- spec/user_spec.cr
- src/placeos-models/user.cr
https://github.com/PlaceOS/models/issues/136
> feat(user): add department and preferred_language

- shard.yml
- src/placeos-models/base/model.cr
- src/placeos-models/module.cr
- src/placeos-models/user_jwt.cr
Adds generators for OpenAPI schemas to each model (including submodels)
> feat: add openapi-serializable

- shard.yml
- spec/edge_spec.cr
- spec/generator.cr
- src/placeos-models/edge.cr
- src/placeos-models/user_jwt.cr
Refactor edges to use an ApiKey instead of its own issued token
Component of https://github.com/PlaceOS/rest-api/issues/174
> refactor: edge api key

- shard.yml
- spec/edge_spec.cr
- spec/generator.cr
- src/placeos-models/edge.cr
This is cleaner behaviour regarding cleanup of the associated key
> refactor(edge): move key clean-up to `save!`

- shard.override.yml
- shard.yml
- spec/helper.cr
- spec/trigger_spec.cr
- src/ext/bcrypt.cr
- src/placeos-models.cr
- src/placeos-models/settings.cr
- src/placeos-models/user.cr
Add `JSON::Serializable` and `YAML::Serializable`
**Benefits**
Helps with OpenAPI generation
https://github.com/PlaceOS/rest-api/issues/251
> build!: update active-model and rethinkdb-orm

- src/placeos-models/base/jwt.cr
- src/placeos-models/base/model.cr
- src/placeos-models/edge.cr
- src/placeos-models/metadata.cr
- src/placeos-models/trigger/conditions.cr
- src/placeos-models/user.cr
- src/placeos-models/user_jwt.cr
- src/placeos-models/version.cr
Models will be able to generate schema with the OpenAPI generator
> feat(model): produce model schema

- .github/workflows/autolabel.yml
- spec/metadata_spec.cr
- src/placeos-models/metadata.cr
Refactor metadata creation and updates, moving logic from the controller to the model.
> refactor(metadata): creation/update helpers

- spec/metadata_spec.cr
- src/placeos-models/metadata.cr
- src/placeos-models/trigger/conditions.cr
- src/placeos-models/user_jwt.cr
Removes the `JSON::Any::StringConverter`
- Related #156
> refactor!(metadata): remove string backed `details` object

- spec/metadata_spec.cr
- src/placeos-models/metadata.cr
Option to query `name=<name>`, which filters metadata under that name
> feat(metadata#query): add ability to filter by name

- spec/generator.cr
- spec/helper.cr
- spec/module_spec.cr
- src/placeos-models/user.cr
Resolves a bug introduced in #123
> fix(User#find_by_email): digest was not used

- spec/api_key_spec.cr
- spec/asset_instance_spec.cr
- spec/asset_spec.cr
- spec/authority_spec.cr
- spec/broker_spec.cr
- spec/control_system_spec.cr
- spec/driver_spec.cr
- spec/edge_spec.cr
- spec/generator.cr
- spec/helper.cr
- spec/json_schema_spec.cr
- spec/metadata_spec.cr
- spec/module_spec.cr
- spec/repository_spec.cr
- spec/settings_spec.cr
- spec/trigger_instance_spec.cr
- spec/trigger_spec.cr
- spec/user_spec.cr
- spec/zone_spec.cr
- src/placeos-models/trigger_instance.cr
- src/placeos-models/utilities/last_modified.cr
- Ensures the modifying user's id is serialised in the response
- Adds specs to ensure that the round-trip property in serialisation is upheld
> fix(last_modified): ensure `modified_by_id` is serialised

- shard.yml
- src/placeos-models/user.cr
as requests are authenticated and internal staff require access to this data to perform their day to day jobs
relates to place-technology/suncorp-ntt#198
> feat(user): expose commonly required fields

- spec/metadata_spec.cr
- src/ext/json.cr
- src/placeos-models/metadata.cr
Implements a merge operation in accordance with [JSON Merge Patch RFC7396](https://www.rfc-editor.org/rfc/rfc7396.html)
- Resolves https://github.com/place-technology/suncorp-ntt/issues/182
> feat: `Metadata#details` merge

- docker-compose.yml
Added entry for `shard.yml.input`
> fix: docker-compose file entry for shard.yml.input

- shard.yml
- src/placeos-models/user.cr
useful for staff to use internally
> feat(user): expose email and phone number

- shard.yml
- src/placeos-models/control_system.cr
for managing public chat rooms
FYI @naqvis can you port this change to the Postgres version?
> feat(control_system): add public flag

- shard.yml
- src/placeos-models/base/jwt.cr
if the private key is the only key provided
> fix(base/jwt): generate public key from private

- migration/db/migrations/20230605110900_alter_assets_add_zone_id.sql
- spec/asset_spec.cr
- spec/generator.cr
- src/placeos-models/asset.cr
- src/placeos-models/booking.cr
- src/placeos-models/event_metadata.cr
ensures bookings are rejected when an asset is deleted
> feat: link assets to zones and clean up bookings

- spec/asset_spec.cr
ensures a minimal asset can be saved
> chore(asset): add a minimal asset save test

- migration/db/migrations/20230827000001_alter_doorkeeper_table_and_add_skip_authorization.sql
- src/placeos-models/doorkeeper_application.cr
Adds a `skip_authorization` field to the Doorkeeper model
> fix: Add skip_authorization field to the Doorkeeper

- spec/upload_spec.cr
- src/placeos-models/upload.cr
validates file names should work in browsers and major OS's without issue.
> feat(upload): ensures upload file names are valid across systems

- spec/asset_spec.cr
- spec/event_linked_bookings_spec.cr
- src/placeos-models/booking.cr
> fix(booking): check for clashing in a transaction PPT-931

- src/placeos-models/attendee.cr
this is a one way sync as any booking can have multiple attendees associated with it
> feat(attendee): ensure booking checked in if guest is [PPT-861]

- migration/db/migrations/202312150022100_event_meta_add_resource_master.sql
- spec/event_metadata_spec.cr
- spec/generator.cr
- src/placeos-models/event_metadata.cr
> feat(event_metadata): allows lookup of recurring master events

- spec/generator.cr
- spec/survey_invitation_spec.cr
- spec/survey_question_spec.cr
- spec/survey_spec.cr
- src/placeos-models/survey/invitation.cr
Adds tests to survey models and fixes listing unsent invitations.
> fix(survey): make Survey::Invitation.list(sent: false) return unsent invites

- src/placeos-models/driver.cr
> fix(driver): remove flag if commits match

- migration/db/migrations/202408060000000_alter_uploads_more_metadata.sql
- src/placeos-models/playlist/item.cr
field for storing full playback time for a video and model to allow for responding Upload details
> feat(playlist/item): add video length

- spec/booking_recurring_spec.cr
- src/placeos-models/booking.cr
where an instance is effectively deleted but the start and end times are unmodified
> fix(booking): recurring booking clash check [PPT-1520]

- src/placeos-models/asset_type.cr
causing 500 errors when an entry has a nil column
> fix(asset_type): images is nilable in the database

- spec/settings_spec.cr
- src/placeos-models/booking.cr
- src/placeos-models/settings.cr
- src/placeos-models/tenant.cr
as YAML can have objects as keys whereas JSON can only have strings
also fix a spelling mistake in docs
> fix(settings): validate yaml to json conversion [PPT-1873]
